### ISSUE TITLE
Unable to start any games of Snowstorm

### ISSUE THREAD

**Issue by jtieri** [Quackster/Havana#38]
I can create a game for Snowstorm, have players join the teams but then when I attempt to start the game no one is taken to the lobby and in the game menu it will show the game is started.

This log is printed when attempting to start the game.
```
2023-04-29T22:20:40.883 ERROR [ErrorLogger] - Error occurred when handling (170) for user (test):
java.lang.NullPointerException: Cannot invoke "org.alexdev.havana.game.games.snowstorm.mapping.SnowStormMap.getItems()" because the return value of "org.alexdev.havana.game.games.snowstorm.SnowStormGame.getMap()" is null
        at org.alexdev.havana.game.games.snowstorm.SnowStormGame.initialise(SnowStormGame.java:91)
        at org.alexdev.havana.game.games.Game.startGame(Game.java:147)
        at org.alexdev.havana.messages.incoming.games.STARTGAME.handle(STARTGAME.java:55)
        at org.alexdev.havana.messages.MessageHandler.invoke(MessageHandler.java:589)
        at org.alexdev.havana.messages.MessageHandler.handleRequest(MessageHandler.java:568)
        at org.alexdev.havana.server.netty.connections.ConnectionHandler.channelRead0(ConnectionHandler.java:104)
        at org.alexdev.havana.server.netty.connections.ConnectionHandler.channelRead0(ConnectionHandler.java:21)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jtieri** [comment]
I realized that I didn't have the maps on my remote server which is why it wasn't working there but it worked locally. Closing this out!
