### ISSUE TITLE
havana server issue

### ISSUE THREAD

**Issue by Al0ne-collab** [Quackster/Havana#45]
I got error when i run havana server
```
2024-03-12T14:42:27.911 INFO  [org.alexdev.havana.Havana] - Setting up game
Exception occurred for definition: 1
java.lang.IllegalArgumentException: No enum constant org.alexdev.havana.game.item.base.ItemBehaviour.SOLİD
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.alexdev.havana.game.item.base.ItemBehaviour.valueOf(ItemBehaviour.java:3)
	at org.alexdev.havana.game.item.base.ItemDefinition.parseBehaviour(ItemDefinition.java:120)
	at org.alexdev.havana.game.item.base.ItemDefinition.<init>(ItemDefinition.java:60)
	at org.alexdev.havana.dao.mysql.ItemDao.getItemDefinitions(ItemDao.java:43)
	at org.alexdev.havana.game.item.ItemManager.<init>(ItemManager.java:33)
	at org.alexdev.havana.game.item.ItemManager.getInstance(ItemManager.java:199)
	at org.alexdev.havana.Havana.main(Havana.java:129)
Exception occurred for definition: 2
java.lang.IllegalArgumentException: No enum constant org.alexdev.havana.game.item.base.ItemBehaviour.SOLİD
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.alexdev.havana.game.item.base.ItemBehaviour.valueOf(ItemBehaviour.java:3)
	at org.alexdev.havana.game.item.base.ItemDefinition.parseBehaviour(ItemDefinition.java:120)
	at org.alexdev.havana.game.item.base.ItemDefinition.<init>(ItemDefinition.java:60)
	at org.alexdev.havana.dao.mysql.ItemDao.getItemDefinitions(ItemDao.java:43)
	at org.alexdev.havana.game.item.ItemManager.<init>(ItemManager.java:33)
	at org.alexdev.havana.game.item.ItemManager.getInstance(ItemManager.java:199)
	at org.alexdev.havana.Havana.main(Havana.java:129)
Exception occurred for definition: 3
java.lang.IllegalArgumentException: No enum constant org.alexdev.havana.game.item.base.ItemBehaviour.SOLİD
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.alexdev.havana.game.item.base.ItemBehaviour.valueOf(ItemBehaviour.java:3)
	at org.alexdev.havana.game.item.base.ItemDefinition.parseBehaviour(ItemDefinition.java:120)
	at org.alexdev.havana.game.item.base.ItemDefinition.<init>(ItemDefinition.java:60)
	at org.alexdev.havana.dao.mysql.ItemDao.getItemDefinitions(ItemDao.java:43)
	at org.alexdev.havana.game.item.ItemManager.<init>(ItemManager.java:33)
	at org.alexdev.havana.game.item.ItemManager.getInstance(ItemManager.java:199)
	at org.alexdev.havana.Havana.main(Havana.java:129)
Exception occurred for definition: 4
java.lang.IllegalArgumentException: No enum constant org.alexdev.havana.game.item.base.ItemBehaviour.SOLİD
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.alexdev.havana.game.item.base.ItemBehaviour.valueOf(ItemBehaviour.java:3)
	at org.alexdev.havana.game.item.base.ItemDefinition.parseBehaviour(ItemDefinition.java:120)
	at org.alexdev.havana.game.item.base.ItemDefinition.<init>(ItemDefinition.java:60)
	at org.alexdev.havana.dao.mysql.ItemDao.getItemDefinitions(ItemDao.java:43)
	at org.alexdev.havana.game.item.ItemManager.<init>(ItemManager.java:33)
	at org.alexdev.havana.game.item.ItemManager.getInstance(ItemManager.java:199)
	at org.alexdev.havana.Havana.main(Havana.java:129)
Exception occurred for definition: 5
java.lang.IllegalArgumentException: No enum constant org.alexdev.havana.game.item.base.ItemBehaviour.CAN_SİT_ON_TOP
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.alexdev.havana.game.item.base.ItemBehaviour.valueOf(ItemBehaviour.java:3)
	at org.alexdev.havana.game.item.base.ItemDefinition.parseBehaviour(ItemDefinition.java:120)
	at org.alexdev.havana.game.item.base.ItemDefinition.<init>(ItemDefinition.java:60)
	at org.alexdev.havana.dao.mysql.ItemDao.getItemDefinitions(ItemDao.java:43)
	at org.alexdev.havana.game.item.ItemManager.<init>(ItemManager.java:33)
	at org.alexdev.havana.game.item.ItemManager.getInstance(ItemManager.java:199)
	at org.alexdev.havana.Havana.main(Havana.java:129)
2024-03-12T14:42:28.056 ERROR [ErrorLogger] - Error when executing MySQL query: 
java.lang.IllegalArgumentException: No enum constant org.alexdev.havana.game.item.interactors.InteractionType.CHAİR
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.alexdev.havana.game.item.interactors.InteractionType.valueOf(InteractionType.java:16)
	at org.alexdev.havana.game.item.base.ItemDefinition.<init>(ItemDefinition.java:61)
	at org.alexdev.havana.dao.mysql.ItemDao.getItemDefinitions(ItemDao.java:43)
	at org.alexdev.havana.game.item.ItemManager.<init>(ItemManager.java:33)
	at org.alexdev.havana.game.item.ItemManager.getInstance(ItemManager.java:199)
	at org.alexdev.havana.Havana.main(Havana.java:129)
Item 2051 (hc2_armchair) has an invalid definition id: 1864
Item 1553 (poster_1006) has an invalid definition id: 251
Item 2075 (basket) has an invalid definition id: 1888
Item 2078 (rare_mnstr) has an invalid definition id: 1891
Item 2079 (rare_beehive_bulb*3) has an invalid definition id: 1892
Item 1603 (hween09_organ) has an invalid definition id: 1448
Item 1604 (sf_mbar) has an invalid definition id: 1449
Item 1605 (rare_xmas_screen) has an invalid definition id: 1458
Item 1606 (valentinescreen) has an invalid definition id: 1459
Item 1607 (beanstalk) has an invalid definition id: 1450
Item 1608 (djesko_turntable) has an invalid definition id: 1451
Item 585 (rubberchair*1) has an invalid definition id: 496
Item 1609 (rare_globe) has an invalid definition id: 1452
Item 586 (rubberchair*2) has an invalid definition id: 497
Item 1610 (rare_hammock) has an invalid definition id: 1453
Item 587 (rubberchair*3) has an invalid definition id: 498
Item 1611 (rare_ironmaiden) has an invalid definition id: 1454
Item 588 (rubberchair*4) has an invalid definition id: 499
Item 1612 (rare_mmmth) has an invalid definition id: 1455
Item 589 (rubberchair*5) has an invalid definition id: 500
Item 1613 (rare_stand) has an invalid definition id: 1456
Item 590 (rubberchair*6) has an invalid definition id: 501
Item 1614 (rare_vdoll) has an invalid definition id: 1457
Item 591 (rubberchair*7) has an invalid definition id: 502
Item 1615 (hween09_wall1) has an invalid definition id: 1474
Item 592 (rubberchair*8) has an invalid definition id: 503
Item 1616 (hween09_win) has an invalid definition id: 1475
Item 593 (spyro) has an invalid definition id: 504
Item 1617 (hween09_chair) has an invalid definition id: 1460
```

**Comment by Al0ne-collab** [comment]
solved turkish alphabet problem
